//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FriendConnections> FriendConnections { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<InvationDesktop> InvationDesktop { get; set; }
        public virtual DbSet<Man> Man { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<Step> Step { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
