//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvationDesktop
    {
        public int InvID { get; set; }
        public int AdminUserID { get; set; }
        public string DName { get; set; }
        public string DPass { get; set; }
        public Nullable<int> User1 { get; set; }
        public Nullable<int> User2 { get; set; }
        public Nullable<int> User3 { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User4 { get; set; }
        public virtual User User5 { get; set; }
        public virtual User User6 { get; set; }
    }
}
