//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.Man = new HashSet<Man>();
        }
    
        public int PlayerID { get; set; }
        public int UserID { get; set; }
        public int GameID { get; set; }
        public Nullable<int> IsWinner { get; set; }
        public Nullable<int> Dice1 { get; set; }
        public Nullable<int> Dice2 { get; set; }
        public string Status { get; set; }
        public string Color { get; set; }
    
        public virtual Game Game { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Man> Man { get; set; }
        public virtual User User { get; set; }
    }
}
