//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        public int StepID { get; set; }
        public int ManID { get; set; }
        public Nullable<int> FromPoz { get; set; }
        public Nullable<int> ToPoz { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    
        public virtual Man Man { get; set; }
    }
}
